### ISSUE TITLE
[BUG] gio-sys 0.21.2 appears to not be compatible with C glib 2.86.0

### ISSUE THREAD

**Issue by jbicha** [gtk-rs/gtk-rs-core#1815]
**Bug description**

I am unable to build rust-gio-sys 0.21.2 on Ubuntu 25.04 which has the C library [glib](https://launchpad.net/ubuntu/+source/glib2.0) at 2.86.0. This issue also affect rust-gio-sys 0.21.1 but I somewhat expected that version not to work since it was released "early" and glib made breaking changes in the 2.85/2.86 development cycle very late.

rust-gio-sys 0.21.1 did build in Ubuntu 25.04 with glib 2.85.4 (the last glib prerelease before 2.86.0). Also rust-gio-sys does build successfully in Debian Unstable which still has glib 2.84.4. I expect that a fix for this issue might make it so that rust-gio-sys does not build with versions of glib older than 2.86.0

**Excerpt**

```
error[E0412]: cannot find type `GUnixMountEntry` in this scope
   --> src/manual.rs:184:22
    |
184 |         mount1: *mut GUnixMountEntry,
    |                      ^^^^^^^^^^^^^^^ not found in this scope
```

**Logs**

Click amd64 at
https://launchpad.net/ubuntu/+source/rust-gio-sys/0.21.2-1

**Other Info**
Debian and Ubuntu do use distro gir files to build these packages, but have [copied](https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/gio-sys/debian/rules) the tweaks from gir-files fix.sh.

**Comment by sdroege** [comment]
> Debian and Ubuntu do use distro gir files to build these packages, but have [copied](https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/gio-sys/debian/rules) the tweaks from gir-files fix.sh.

That's exactly the problem. Don't do that. Doing so would pull in the changes from https://github.com/gtk-rs/gir-files/pull/262, which require considerable changes on our side and would result in breaking changes in the bindings (`GUnixMountEntry` etc would move to their separate `gio-unix` crate).

The corresponding change on the bindings side will be released together with 0.22 next summer.
