### ISSUE TITLE
regression from #116

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs-core#127]
see https://github.com/gtk-rs/gtk-rs-core/pull/116#issuecomment-855253011

logs from gtk4-rs examples:
``` 

error[E0433]: failed to resolve: use of undeclared crate or module `glib`
  --> examples/grid_packing/main.rs:49:33
   |
49 |     quit_button.connect_clicked(clone!(@weak window => move |_| window.destroy()));
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `glib`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `glib`
  --> examples/grid_packing/main.rs:49:33
   |
49 |     quit_button.connect_clicked(clone!(@weak window => move |_| window.destroy()));
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `glib::clone`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this trait
   |
1  | use crate::clone::Downgrade;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `glib`
  --> examples/grid_packing/main.rs:49:33
   |
49 |     quit_button.connect_clicked(clone!(@weak window => move |_| window.destroy()));
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `glib::clone`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this trait
   |
1  | use crate::clone::Upgrade;
   |

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `gtk4-rs-examples`
```

**Comment by fengalin** [comment]
After a quick check, this is how I see it:

- https://github.com/gtk-rs/gtk-rs-core/pull/116 attempted at fixing an issue found in `gst-plugins-rs/utils` where `glib-macros/utils::crate_ident_new` prepended `gtk` to `glib` within the macro `#[glib::object_subclass]`. The problem is `gtk` is optional for those crates. They use `glib` via `gst::glib` which is always available.
- `crate_ident_new` relies on `proc-macro-crate::crate_name`, which doesn't check whether a dependency is actually selected. Since `gtk` is declared before `gstreamer` in the `KNOWN_GLIB_EXPORTS`, `gtk` is selected by `crate_ident_new` leading to `gtk::glib` being used within `#[glib::object_subclass]`, which fails to compile when `gtk` is not selected.
- https://github.com/gtk-rs/gtk-rs-core/pull/116 fixed the compilation failure and I had to `use gst::glib` explicitly. However, the fix is wrong since it removed a use case to prevent another use case from failing.
- I doubt `proc-macro-crate` can be updated to detect whether a dependency is actually selected. `proc-macro-crate` parses `Cargo.toml` to analyze the dependencies. It has no clue whether a `feature` is selected that would lead to using a dependency.
- I think the only viable solution for this is to let developers explicitly select which dependency should be used as a provider for `glib`. IMO, this is very limited an inconvenience since the compiler points to the exact problem (see error messages in this PR's comment).
- If we decide to go this route, `crate_ident_new` is probably no longer needed.

**Comment by bilelmoussaoui** [comment]
As discussed in Matrix, the situation is not as bad as I thought. we just need to have glib in scope (with `use gtk::glib::{self, clone}` and in general, you need type from glib anyway. 

I will go ahead and close this one, as I don't think there's any way to workaround the current situation without breaking other use cases.

**Comment by GuillaumeGomez** [comment]
Might be worth updating the documentation of the macro though.

**Comment by bilelmoussaoui** [comment]
That's not clone specific though. all the other glib macros require the same thing now

**Comment by GuillaumeGomez** [comment]
Then we need to update all their documentation. :)
